name: kitchen_companion
description: "A companion to help you prepare your cooks."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  camera: ^0.10.6
  flutter:
    sdk: flutter
  google_mlkit_barcode_scanning: ^0.12.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
